Django/Game/IPL/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('posts/list/', views.index, name='index'),
    path('posts/<id>', views.post_detail, name='post_detail'),
    path('posts/<id>/delete', views.delete_post, name='delete_post'),

    path('posts/add/', views.post_add),
    path('about/', views.about),
    path('teams/', views.teams),
    path('teams/<id>', views.team_detail),
]

Django/Game/gameproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('IPL.urls')),
    
    # production server static and media files
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
] 

# development static and media files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/Todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todoapp/', include('todoapp.urls')),
]

Django/project1/project1/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Django/tailwindproject/todoapp/models.py
from django.db import models


class Todo(models.Model):
    title = models.CharField(max_length=100, blank=False)
    desc = models.TextField(null = True, blank = True)
    status = models.CharField(max_length=100, default = 'Pending')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Django/todoproject/todoapp/models.py
from django.db import models

# Create your models here.


class Todos(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self) :
        return self.title



    

Django/Todo/todoapp/views.py
from django.shortcuts import redirect, render, HttpResponse

from .models import Todo


def list(request):
    
    queryset =  Todo.objects.all()

    print(queryset.query)

    context = {
        "todos": queryset
    }
    return render(request, 'list-todo.html',context)



def create(request):
    # Todo.objects.create(desc="dummy desc")
    print(request.GET.get('text'))
    print(request.GET.get('csrfmiddlewaretoken'))
 
    if request.method == 'POST':
        title = request.POST.get('title')
        text = request.POST.get('text')
        Todo.objects.create(title=title, desc=text)
        return redirect('/todoapp')
    

    return render(request, 'create-todo.html')


def update(request, id):
    todo =  Todo.objects.get(id=id)
    
    if request.method == 'POST':
        title = request.POST.get('title')
        text = request.POST.get('text')
        status = request.POST.get('status')

        todo.title = title
        todo.desc=  text
        todo.status = status

        todo.save()

        return redirect('/todoapp')
    
    return render(request, 'update-todo.html', {'todo': todo})
  


def delete(request, id):
    # todo =  Todo.objects.get(id=id)
    # todo.delete()
    # return redirect('/todoapp')
    return HttpResponse(id)

Django/tailwindproject/todoapp/views.py
from django.shortcuts import redirect, render, HttpResponse

from .models import Todo


def list(request):
    
    queryset =  Todo.objects.all()

    print(queryset.query)

    context = {
        "todos": queryset
    }
    return render(request, 'list-todo.html',context)



def create(request):
    # Todo.objects.create(desc="dummy desc")
    print(request.GET.get('text'))
    print(request.GET.get('csrfmiddlewaretoken'))
 
    if request.method == 'POST':
        title = request.POST.get('title')
        text = request.POST.get('text')
        print(title, text, 'title, text')
        Todo.objects.create(title=title, desc=text)
        return redirect('/todoapp')
    

    return render(request, 'create-todo.html')


def update(request, id):
    todo =  Todo.objects.get(id=id)
    
    if request.method == 'POST':
        title = request.POST.get('title')
        text = request.POST.get('text')
        status = request.POST.get('status')

        todo.title = title
        todo.desc=  text
        todo.status = status

        todo.save()

        return redirect('/todoapp')
    
    return render(request, 'update-todo.html', {'todo': todo})
  


def delete(request, id):
    # todo =  Todo.objects.get(id=id)
    # todo.delete()
    # return redirect('/todoapp')
    return HttpResponse(id)

Django/todoproject/todoapp/views.py
from django.shortcuts import redirect, render
from .models import Todos
from django.http import HttpResponse, Http404
from django.contrib import messages
# Create your views here.

def index(request, **kwargs):
    queryset = Todos.objects.all()
    return render(request, 'todos.html', {'todos': queryset})

def create(request):
    return render(request, 'create.html')

def save(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        status = request.POST.get('status')
        todo = Todos.objects.create(
            title=title,
            description=description,
            status="pending"
        )
        todo.save()
        messages.success(request, 'Todo created successfully')
        return redirect('todos')
    else:
        return HttpResponse('Method not allowed. Use POST') 

def delete(request, id):
    todo = Todos.objects.get(id=id)
    todo.delete()
    messages.success(request, 'Todo deleted successfully')
    return  redirect('todos')

def edit(request, id):
    todo = Todos.objects.get(id=id)
    return render(request, 'edit.html', {'todo': todo})

def update(request, id):
    todo = Todos.objects.get(id=id)
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        status = request.POST.get('status')
        todo.title = title
        todo.description = description
        todo.status = status
        todo.save()
        messages.success(request, 'Todo updated successfully')
        return redirect('todos')
    else:
        return HttpResponse('Method not allowed. Use POST')

Django/todoproject/todoapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Todo App{% endblock %}</title>
    <!-- load bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>    
<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Todo App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'todos' %}">Todos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'create' %}">Create</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
       

    
      <div class="container mt-2">
         {% for message in messages %}
         <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-2" role="alert">
                 {{ message | safe }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
    {% endfor %}
        {% block content %}
        {% endblock %}
    </div>

  
 

    <script src="{% static 'js/action.js' %}"></script>
</body>
</html>

Django/todoproject/todoapp/templates/create.html
 {% extends 'base.html' %}
{% block title %}Create Todo App{% endblock %}
{% block content %}
 <h2>Create a Todo</h2>
  <form method="post" action="{% url 'save' %}" class="mb-3">
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="id_title">Title</label>
      <input type="text" name="title" id="id_title" class="form-control" required>
    </div>
    <div class="form-group mb-3">
      <label for="id_description">Description</label>
      <textarea name="description" id="id_description" class="form-control" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
  </form>
{% endblock %}

Django/todoproject/todoapp/templates/edit.html
{% extends 'base.html' %}
{% block title %}Edit Todo App{% endblock %}
{% block content %}
<h2>Edit Todo</h2>
<form method="post" action="{% url 'update' todo.id %}" class="mb-3">
  {% csrf_token %}
  <div class="form-group mb-3">
    <label for="id_title">Title</label>
    <input type="text" name="title" id="id_title" class="form-control" value="{{ todo.title }}" required>
  </div>
  <div class="form-group mb-3">
    <label for="id_description">Description</label>
    <textarea name="description" id="id_description" class="form-control" rows="3">{{ todo.description }}</textarea>
  </div>
  <div class="form-group mb-3">
    <label for="id_status">Status</label>
    <select name="status" id="id_status" class="form-control">
      <option value="pending" {% if todo.status == 'pending' %}selected{% endif %}>Pending</option>
      <option value="completed" {% if todo.status == 'completed' %}selected{% endif %}>Completed</option>
    </select>
  </div>
  <button type="submit" class="btn btn-primary">Edit</button>
</form>
{% endblock %}

Django/todoproject/todoapp/templates/todos.html
{% extends 'base.html' %}
{% block title %}Todo App{% endblock %}

{% block content %}





  <h2>Todo List</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Sr.</th>
        <th>Title</th>
        <th>Description</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for todo in todos %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ todo.title }}</td>
        <td>{{ todo.description }}</td>
        <td>{{ todo.status }}</td>
        <td>
          <a href="{% url 'delete' todo.id %}">Delete</a> |
          <a href="{% url 'edit' todo.id %}">Edit</a>
        </td>
      </tr>
       {% empty %}
      <tr>
        <td colspan="4">No todos found.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock content %}